name: DeepRBP
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - anyio=4.2.0
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=23.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=4.1.0
  - brotli-python=1.0.9
  - ca-certificates=2024.3.11
  - cffi=1.16.0
  - comm=0.2.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - filelock=3.13.1
  - freetype=2.12.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - idna=3.4
  - importlib_metadata=7.0.1
  - intel-openmp=2023.1.0
  - ipykernel=6.28.0
  - ipython=8.15.0
  - jedi=0.18.1
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - jupyter_events=0.8.0
  - jupyter_server=2.10.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.11
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - lcms2=2.12
  - lerc=3.0
  - libcxx=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libjpeg-turbo=2.0.0
  - libpng=1.6.39
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.1
  - notebook=7.0.8
  - notebook-shim=0.2.3
  - openjpeg=2.4.0
  - openssl=3.0.13
  - overrides=7.4.0
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - platformdirs=3.10.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pysocks=1.7.1
  - python=3.9.19
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - pytorch=2.2.2
  - pyzmq=25.1.2
  - readline=8.2
  - referencing=0.30.2
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - send2trash=1.8.2
  - setuptools=68.2.2
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - stack_data=0.2.0
  - sympy=1.12
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - torchaudio=2.2.2
  - torchvision=0.17.2
  - tornado=6.3.3
  - traitlets=5.7.1
  - typing_extensions=4.9.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.41.2
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - alembic==1.11.0
      - appdirs==1.4.4
      - blinker==1.6.2
      - captum==0.4.0
      - certifi==2023.5.7
      - chardet==5.2.0
      - charset-normalizer==3.1.0
      - click==8.1.3
      - cloudpickle==2.2.1
      - cmaes==0.9.1
      - colorlog==6.7.0
      - contourpy==1.0.7
      - cycler==0.11.0
      - databricks-cli==0.17.7
      - docker==6.1.2
      - docker-pycreds==0.4.0
      - entrypoints==0.4
      - et-xmlfile==1.1.0
      - flask==2.3.2
      - fonttools==4.39.4
      - fsspec==2024.3.1
      - future==0.18.3
      - gitdb==4.0.10
      - gitpython==3.1.31
      - greenlet==2.0.2
      - gunicorn==20.1.0
      - hyperopt==0.2.7
      - importlib-metadata==6.6.0
      - importlib-resources==5.12.0
      - install==1.3.5
      - itsdangerous==2.1.2
      - jinja2==3.1.2
      - joblib==1.2.0
      - kiwisolver==1.4.4
      - llvmlite==0.40.1
      - mako==1.2.4
      - markdown==3.4.3
      - markupsafe==2.1.2
      - matplotlib==3.7.1
      - matplotlib-venn==0.11.10
      - mlflow==2.3.2
      - numba==0.57.1
      - numpy==1.24.3
      - oauthlib==3.2.2
      - openpyxl==3.1.2
      - optuna==3.1.1
      - packaging==23.1
      - pandas==1.5.3
      - pathtools==0.1.2
      - patsy==0.5.3
      - pillow==9.5.0
      - plotly==5.14.1
      - protobuf==4.23.0
      - psutil==5.9.5
      - py4j==0.10.9.7
      - pyaml==23.5.9
      - pyarrow==11.0.0
      - pyjwt==2.7.0
      - pynndescent==0.5.10
      - pyparsing==3.0.9
      - pytz==2023.3
      - pyyaml==6.0
      - qnorm==0.8.1
      - querystring-parser==1.2.4
      - requests==2.30.0
      - scikit-learn==1.2.2
      - scikit-optimize==0.9.0
      - scipy==1.10.1
      - seaborn==0.11.2
      - sentry-sdk==1.23.0
      - setproctitle==1.3.2
      - smmap==5.0.0
      - sqlalchemy==2.0.13
      - sqlparse==0.4.4
      - statannot==0.2.3
      - statannotations==0.6.0
      - statsmodels==0.14.0
      - tabulate==0.9.0
      - tbb==2021.10.0
      - tenacity==8.2.2
      - threadpoolctl==3.1.0
      - tqdm==4.65.0
      - typing-extensions==4.5.0
      - tzdata==2023.3
      - umap==0.1.1
      - umap-learn==0.5.4
      - upsetplot==0.9.0
      - urllib3==1.26.15
      - venny4py==1.0.0
      - wandb==0.15.1
      - websocket-client==1.5.1
      - werkzeug==2.3.4
      - zipp==3.15.0
